### PR TITLE
Add notify for copy to clipboard

### PR DESCRIPTION
**Pull request by RuanAragao**
Notify animated
image

### CODE REVIEW

**Comment by crisgon** [comment]
Use a tooltip!!

**Comment by vini23hot** [comment]
@rafa-acioly yeah... I didn't like too. When I go home, i'll review this PR and comment the changes needed.

**Comment by rafa-acioly** [comment]
cool @vini23hot.

@RuanAragao can you send a PR using `tooltip`?

**Comment by RuanAragao** [comment]
I did the substitution for `tooltip`, I hope you are more agreeable.

**Pull request merged**
